### ISSUE TITLE
php7.4  notices

### ISSUE THREAD

**Issue by gtbu** [TN03/hi_admin_xh#5]
Only in php 7.4 - so not so urgent - just makes a long xdebug-list
NOTICE: Undefined index: hi_admin
((    I:\Xampp74\inst\htdocs\xhclean\cmsimple\classes\PluginConfig.php:72
NOTICE: Trying to access array offset on value of type null  ))
I:\Xampp74\inst\htdocs\xhclean\plugins\hi_admin_xh\admin.php:32
NOTICE: Trying to access array offset on value of type null
I:\Xampp74\inst\htdocs\xhclean\plugins\hi_admin_xh\admin.php:41
NOTICE: Trying to access array offset on value of type null
I:\Xampp74\inst\htdocs\xhclean\plugins\hi_admin_xh\admin.php:44
NOTICE: Trying to access array offset on value of type null
I:\Xampp74\inst\htdocs\xhclean\plugins\hi_admin_xh\admin.php:47

Evtl.  $plugin_cf['hi_admin']  is zero ?

**Comment by TN03** [comment]
> Evtl. $plugin_cf['hi_admin'] is zero ?

Hmm checked that now with PHP 7.4.1 on a new installed XH 1.72 installation. I can't find that notices (again: not errors). Please provide more informations on how to reproduce.

But I found the deprecated-warning for magic_quotes_gpc() in functions.php and a few notices and warnings in the filebrowser and the meta-tags plugins with PHP 7.4.1. I'll fill an issue about that in the xh-repo later.

**Comment by gtbu** [comment]
I get this error after login at XH-1.72 and Xampp 7.4 (xampp-windows-x64-7.4.1-0-VC15-installer.exe - w10-1803- with and without fhs-admin)
![notice74](https://user-images.githubusercontent.com/30436307/73599108-3ead7500-4540-11ea-9630-6ca1b6d5c01e.jpg)

The notice  is also in other Cms'es.

**Comment by gtbu** [comment]
The error was timely at xampp74 - happened no more - neither in the new clean xh version - just forget it.
